In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os

In [2]:
os.getcwd()

'/Users/umangpandya'

In [3]:
loan_train  = pd.read_csv('/Users/umangpandya/Downloads/Class 9 - Codes/Project - Classification/Python_Module_Day_15.2_Credit_Risk_Train_data_XTRAIN.csv')

In [4]:
loan_test = pd.read_csv('/Users/umangpandya/Downloads/Class 9 - Codes/Project - Classification/Python_Module_Day_15.4_Credit_Risk_Validate_data_XTEST.csv')

In [5]:
loan_predict = pd.read_csv('/Users/umangpandya/Downloads/Class 9 - Codes/Project - Classification/Python_Module_Day_15.3_Credit_Risk_Test_data.csv')

In [6]:
loan_train = pd.DataFrame(loan_train)
loan_train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [7]:
loan_train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

# Data Pre-Processing

In [8]:
from statistics import mode
from statistics import mean
from statistics import median

In [9]:
#filling NAs
loan_train['Gender'].fillna(mode(loan_train['Gender']),inplace = True,axis = 0)
loan_train['Married'].fillna(mode(loan_train['Married']),inplace = True,axis = 0)
loan_train['Dependents'].fillna(mode(loan_train['Dependents']),inplace = True,axis = 0)
loan_train['Self_Employed'].fillna(mode(loan_train['Self_Employed']),inplace = True,axis = 0)
loan_train['Loan_Amount_Term'].fillna(mode(loan_train['Loan_Amount_Term']),inplace = True,axis = 0)
loan_train['Credit_History'].fillna(mode(loan_train['Credit_History']),inplace = True,axis = 0)
loan_train['LoanAmount'].fillna((loan_train['LoanAmount'].mean()),inplace = True,axis = 0)


In [10]:
loan_train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [11]:
loan_train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [12]:
#Dependents has '+3' which is wierdly converting the whole series in to str need to convert that in to 3
loan_train['Dependents'].replace({'3+':3},inplace = True)

In [13]:
#Encoding Categorical Data
loan_train['Gender'] = loan_train['Gender'].astype('category')
loan_train['Gender'] = loan_train['Gender'].cat.codes
loan_train['Married'] = loan_train['Married'].astype('category')
loan_train['Married'] = loan_train['Married'].cat.codes
loan_train['Education'] = loan_train['Education'].astype('category')
loan_train['Education'] = loan_train['Education'].cat.codes
loan_train['Self_Employed'] = loan_train['Self_Employed'].astype('category')
loan_train['Self_Employed'] = loan_train['Self_Employed'].cat.codes
loan_train['Property_Area'] = loan_train['Property_Area'].astype('category')
loan_train['Property_Area'] = loan_train['Property_Area'].cat.codes
loan_train['Loan_Status'] = loan_train['Loan_Status'].astype('category')
loan_train['Loan_Status'] = loan_train['Loan_Status'].cat.codes


In [14]:
loan_train.drop('Loan_ID',axis = 1,inplace = True)

In [15]:
loan_train.dtypes

Gender                  int8
Married                 int8
Dependents            object
Education               int8
Self_Employed           int8
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area           int8
Loan_Status             int8
dtype: object

In [16]:
loan_train.Dependents = loan_train.Dependents.astype('int')
loan_train.Credit_History = loan_train.Credit_History.astype('int')
loan_train.Loan_Amount_Term = loan_train.Loan_Amount_Term.astype('int')

In [17]:
loan_train.dtypes

Gender                  int8
Married                 int8
Dependents             int64
Education               int8
Self_Employed           int8
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term       int64
Credit_History         int64
Property_Area           int8
Loan_Status             int8
dtype: object

In [18]:
#Pre-Processing finished on Train Data
loan_train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0           0          0              0             5849   
1         1        1           1          0              0             4583   
2         1        1           0          0              1             3000   
3         1        1           0          1              0             2583   
4         1        0           0          0              0             6000   
5         1        1           2          0              1             5417   
6         1        1           0          1              0             2333   
7         1        1           3          0              0             3036   
8         1        1           2          0              0             4006   
9         1        1           1          0              0            12841   
10        1        1           2          0              0             3200   
11        1        1           2          0              0             2500   
12        1        1           2          0              0             3073   
13        1        0           0          0              0             1853   
14        1        1           2          0              0             1299   
15        1        0           0          0              0             4950   
16        1        0           1          1              0             3596   
17        0        0           0          0              0             3510   
18        1        1           0          1              0             4887   
19        1        1           0          0              0             2600   
20        1        1           0          1              0             7660   
21        1        1           1          0              0             5955   
22        1        1           0          1              0             2600   
23        1        1           2          1              0             3365   
24        1        1           1          0              0             3717   
25        1        1           0          0              1             9560   
26        1        1           0          0              0             2799   
27        1        1           2          1              0             4226   
28        1        0           0          1              0             1442   
29        0        0           2          0              0             3750   
..      ...      ...         ...        ...            ...              ...   
584       1        1           1          0              0             2787   
585       1        1           1          0              0             4283   
586       1        1           0          0              0             2297   
587       0        0           0          1              0             2165   
588       1        0           0          0              0             4750   
589       1        1           2          0              1             2726   
590       1        1           0          0              0             3000   
591       1        1           2          0              1             6000   
592       1        0           3          0              1             9357   
593       1        1           0          0              0             3859   
594       1        1           0          0              1            16120   
595       1        0           0          1              0             3833   
596       1        1           2          1              1             6383   
597       1        0           0          0              0             2987   
598       1        1           0          0              1             9963   
599       1        1           2          0              0             5780   
600       0        0           3          0              0              416   
601       1        1           0          1              0             2894   
602       1        1           3          0            

In [19]:
#Loan_test Data Pre-processing
loan_test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
outcome               0
dtype: int64

In [20]:
#filling NAs
loan_test.Gender = loan_test.Gender.fillna(mode(loan_test.Gender),axis = 0)
loan_test.Dependents = loan_test.Dependents.fillna(mode(loan_test.Dependents),axis = 0)
loan_test.Self_Employed = loan_test.Self_Employed.fillna(mode(loan_test.Self_Employed),axis = 0)
loan_test.LoanAmount = loan_test.LoanAmount.fillna(loan_test.LoanAmount.mean(),axis = 0)
loan_test.Loan_Amount_Term = loan_test.Loan_Amount_Term.fillna(mode(loan_test.Loan_Amount_Term),axis = 0)
loan_test.Credit_History = loan_test.Credit_History.fillna(mode(loan_test.Credit_History),axis = 0)




In [21]:
loan_test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
outcome              0
dtype: int64

In [22]:
loan_test.rename(columns = {'outcome' : 'Loan_Status'}, inplace = True)

In [23]:
#Encoding Categorical Data
loan_test['Gender'] = loan_test['Gender'].astype('category')
loan_test['Gender'] = loan_test['Gender'].cat.codes
loan_test['Married'] = loan_test['Married'].astype('category')
loan_test['Married'] = loan_test['Married'].cat.codes
loan_test['Education'] = loan_test['Education'].astype('category')
loan_test['Education'] = loan_test['Education'].cat.codes
loan_test['Self_Employed'] = loan_test['Self_Employed'].astype('category')
loan_test['Self_Employed'] = loan_test['Self_Employed'].cat.codes
loan_test['Property_Area'] = loan_test['Property_Area'].astype('category')
loan_test['Property_Area'] = loan_test['Property_Area'].cat.codes
loan_test['Loan_Status'] = loan_test['Loan_Status'].astype('category')
loan_test['Loan_Status'] = loan_test['Loan_Status'].cat.codes

In [24]:
loan_test['Dependents'].replace({'3+':3},inplace = True)

In [25]:
loan_test.drop('Loan_ID', axis = 1,inplace = True)

In [26]:
loan_test.dtypes

Gender                  int8
Married                 int8
Dependents            object
Education               int8
Self_Employed           int8
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area           int8
Loan_Status             int8
dtype: object

In [27]:
loan_test.Dependents = loan_test.Dependents.astype('int')
loan_test.Credit_History = loan_test.Credit_History.astype('int')
loan_test.Loan_Amount_Term = loan_test.Loan_Amount_Term.astype('int')
loan_test.CoapplicantIncome = loan_test.CoapplicantIncome.astype('float')

In [28]:
#Pre-Processing finished on Test Data
loan_test

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           0          0              0             5720   
1         1        1           1          0              0             3076   
2         1        1           2          0              0             5000   
3         1        1           2          0              0             2340   
4         1        0           0          1              0             3276   
5         1        1           0          1              1             2165   
6         0        0           1          1              0             2226   
7         1        1           2          1              0             3881   
8         1        1           2          0              0            13633   
9         1        0           0          1              0             2400   
10        1        0           0          1              0             3091   
11        1        1           1          0              0             2185   
12        1        0           3          0              0             4166   
13        1        1           2          0              0            12173   
14        0        0           0          0              0             4666   
15        1        0           1          0              0             5667   
16        1        1           2          0              0             4583   
17        1        1           3          0              0             3786   
18        1        1           0          0              0             9226   
19        1        0           0          0              0             1300   
20        1        1           1          1              0             1888   
21        0        0           3          1              0             2083   
22        1        0           0          0              0             3909   
23        0        0           0          1              0             3765   
24        1        1           0          0              0             5400   
25        1        0           0          0              0                0   
26        1        1           2          0              0             4363   
27        1        1           0          0              0             7500   
28        1        1           0          0              0             3772   
29        1        0           0          0              0             2942   
..      ...      ...         ...        ...            ...              ...   
337       1        1           0          0              0             2292   
338       1        1           1          0              1             2360   
339       0        0           0          0              0             4333   
340       1        1           0          0              1             2623   
341       1        0           0          0              1             3972   
342       1        1           3          1              0             3522   
343       1        1           1          0              0             4700   
344       1        0           0          0              0             6858   
345       1        1           3          0              0             8334   
346       1        1           0          0              0             3391   
347       1        0           0          1              0             2868   
348       1        1           2          1              0             3418   
349       1        1           0          0              1             2500   
350       1        1           2          0              0             8667   
351       1        0           0          0              0             2283   
352       1        1           0          0              0             5817   
353       1        1           0          0              0             5119   
354       1        1           3          1              0             5316   
355       1        1           3          0            

In [29]:
#Pre-processing on predict data
loan_predict.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [30]:
loan_predict.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [31]:
loan_predict.Gender.fillna(mode(loan_predict.Gender),inplace = True, axis = 0)
loan_predict.Dependents.fillna(mode(loan_predict.Dependents),inplace = True, axis = 0)
loan_predict.Self_Employed.fillna(mode(loan_predict.Self_Employed),inplace = True, axis = 0)
loan_predict.LoanAmount.fillna((loan_predict.LoanAmount).mean(),inplace = True, axis = 0)
loan_predict.Loan_Amount_Term.fillna(mode(loan_predict.Loan_Amount_Term),inplace = True, axis = 0)
loan_predict.Credit_History.fillna(mode(loan_predict.Credit_History),inplace = True, axis = 0)

In [32]:
loan_predict.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             1.0         Urban  
4             1.0         Urban

In [33]:
loan_predict.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             1.0         Urban  
4             1.0         Urban

In [34]:
loan_predict.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [35]:
loan_predict['Dependents'].replace({'3+':3},inplace = True)

In [36]:
#Encoding Categorical Data
loan_predict['Gender'] = loan_predict['Gender'].astype('category')
loan_predict['Gender'] = loan_predict['Gender'].cat.codes
loan_predict['Married'] = loan_predict['Married'].astype('category')
loan_predict['Married'] = loan_predict['Married'].cat.codes
loan_predict['Education'] = loan_predict['Education'].astype('category')
loan_predict['Education'] = loan_predict['Education'].cat.codes
loan_predict['Self_Employed'] = loan_predict['Self_Employed'].astype('category')
loan_predict['Self_Employed'] = loan_predict['Self_Employed'].cat.codes
loan_predict['Property_Area'] = loan_predict['Property_Area'].astype('category')
loan_predict['Property_Area'] = loan_predict['Property_Area'].cat.codes


In [37]:
loan_predict.dtypes

Loan_ID               object
Gender                  int8
Married                 int8
Dependents            object
Education               int8
Self_Employed           int8
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area           int8
dtype: object

In [38]:
loan_predict.Dependents = loan_predict.Dependents.astype('int')
loan_predict.Credit_History = loan_predict.Credit_History.astype('int')
loan_predict.Loan_Amount_Term = loan_predict.Loan_Amount_Term.astype('int')
loan_predict.CoapplicantIncome = loan_predict.CoapplicantIncome.astype('float')

In [39]:
loan_predict.dtypes

Loan_ID               object
Gender                  int8
Married                 int8
Dependents             int64
Education               int8
Self_Employed           int8
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term       int64
Credit_History         int64
Property_Area           int8
dtype: object

In [40]:
#Pre-Processing finished on Predict Data
loan_predict

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001015       1        1           0          0              0   
1    LP001022       1        1           1          0              0   
2    LP001031       1        1           2          0              0   
3    LP001035       1        1           2          0              0   
4    LP001051       1        0           0          1              0   
5    LP001054       1        1           0          1              1   
6    LP001055       0        0           1          1              0   
7    LP001056       1        1           2          1              0   
8    LP001059       1        1           2          0              0   
9    LP001067       1        0           0          1              0   
10   LP001078       1        0           0          1              0   
11   LP001082       1        1           1          0              0   
12   LP001083       1        0           3          0              0   
13   LP001094       1        1           2          0              0   
14   LP001096       0        0           0          0              0   
15   LP001099       1        0           1          0              0   
16   LP001105       1        1           2          0              0   
17   LP001107       1        1           3          0              0   
18   LP001108       1        1           0          0              0   
19   LP001115       1        0           0          0              0   
20   LP001121       1        1           1          1              0   
21   LP001124       0        0           3          1              0   
22   LP001128       1        0           0          0              0   
23   LP001135       0        0           0          1              0   
24   LP001149       1        1           0          0              0   
25   LP001153       1        0           0          0              0   
26   LP001163       1        1           2          0              0   
27   LP001169       1        1           0          0              0   
28   LP001174       1        1           0          0              0   
29   LP001176       1        0           0          0              0   
..        ...     ...      ...         ...        ...            ...   
337  LP002856       1        1           0          0              0   
338  LP002857       1        1           1          0              1   
339  LP002858       0        0           0          0              0   
340  LP002860       1        1           0          0              1   
341  LP002867       1        0           0          0              1   
342  LP002869       1        1           3          1              0   
343  LP002870       1        1           1          0              0   
344  LP002876       1        0           0          0              0   
345  LP002878       1        1           3          0              0   
346  LP002879       1        1           0          0              0   
347  LP002885       1        0           0          1              0   
348  LP002890       1        1           2          1              0   
349  LP002891       1        1           0          0              1   
350  LP002899       1        1           2          0              0   
351  LP002901       1        0           0          0              0   
352  LP002907       1        1           0          0              0   
353  LP002920       1        1           0          0              0   
354  LP002921       1        1           3          1              0   
355  LP002932       1        1           3          0              0   
356  LP002935       1        1           1          0              0   
357  LP002952       1        0           0          0              0   
358  LP002954       1        1           2          1              0   
359  LP002962       1        0           0          0              0   
360  LP002965       0        1           0    

In [41]:
loan_train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0             5849   
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162               360               1   
1             1508.0  128.000000               360               1   
2                0.0   66.000000               360               1   
3             2358.0  120.000000               360               1   
4                0.0  141.000000               360               1   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [42]:
loan_test.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             5720   
1       1        1           1          0              0             3076   
2       1        1           2          0              0             5000   
3       1        1           2          0              0             2340   
4       1        0           0          1              0             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       110.0               360               1   
1             1500.0       126.0               360               1   
2             1800.0       208.0               360               1   
3             2546.0       100.0               360               1   
4                0.0        78.0               360               1   

   Property_Area  Loan_Status  
0              2            1  
1              2            1  
2              2            1  
3              2            1  
4              2            0

In [43]:
loan_predict

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001015       1        1           0          0              0   
1    LP001022       1        1           1          0              0   
2    LP001031       1        1           2          0              0   
3    LP001035       1        1           2          0              0   
4    LP001051       1        0           0          1              0   
5    LP001054       1        1           0          1              1   
6    LP001055       0        0           1          1              0   
7    LP001056       1        1           2          1              0   
8    LP001059       1        1           2          0              0   
9    LP001067       1        0           0          1              0   
10   LP001078       1        0           0          1              0   
11   LP001082       1        1           1          0              0   
12   LP001083       1        0           3          0              0   
13   LP001094       1        1           2          0              0   
14   LP001096       0        0           0          0              0   
15   LP001099       1        0           1          0              0   
16   LP001105       1        1           2          0              0   
17   LP001107       1        1           3          0              0   
18   LP001108       1        1           0          0              0   
19   LP001115       1        0           0          0              0   
20   LP001121       1        1           1          1              0   
21   LP001124       0        0           3          1              0   
22   LP001128       1        0           0          0              0   
23   LP001135       0        0           0          1              0   
24   LP001149       1        1           0          0              0   
25   LP001153       1        0           0          0              0   
26   LP001163       1        1           2          0              0   
27   LP001169       1        1           0          0              0   
28   LP001174       1        1           0          0              0   
29   LP001176       1        0           0          0              0   
..        ...     ...      ...         ...        ...            ...   
337  LP002856       1        1           0          0              0   
338  LP002857       1        1           1          0              1   
339  LP002858       0        0           0          0              0   
340  LP002860       1        1           0          0              1   
341  LP002867       1        0           0          0              1   
342  LP002869       1        1           3          1              0   
343  LP002870       1        1           1          0              0   
344  LP002876       1        0           0          0              0   
345  LP002878       1        1           3          0              0   
346  LP002879       1        1           0          0              0   
347  LP002885       1        0           0          1              0   
348  LP002890       1        1           2          1              0   
349  LP002891       1        1           0          0              1   
350  LP002899       1        1           2          0              0   
351  LP002901       1        0           0          0              0   
352  LP002907       1        1           0          0              0   
353  LP002920       1        1           0          0              0   
354  LP002921       1        1           3          1              0   
355  LP002932       1        1           3          0              0   
356  LP002935       1        1           1          0              0   
357  LP002952       1        0           0          0              0   
358  LP002954       1        1           2          1              0   
359  LP002962       1        0           0          0              0   
360  LP002965       0        1           0    

In [44]:
x_train = loan_train.iloc[:,:11].values
y_train = loan_train.iloc[:,11].values
x_test = loan_test.iloc[:,:11].values
y_test = loan_test.iloc[:,11].values


# Logistic Regression


In [45]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression() 
lr.fit(x_train,y_train)


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [46]:
y_pred = lr.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [47]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 58,  19],
       [  1, 289]])

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9455040871934605

# Naive Bayes

In [49]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [50]:
y_pred = nb.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [51]:
confusion_matrix(y_test,y_pred)

array([[ 58,  19],
       [  8, 282]])

In [52]:
accuracy_score(y_test,y_pred)

0.9264305177111717

# K - Nearest Neighbours

In [53]:
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
knc.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [54]:
y_pred = knc.predict(x_test)
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [55]:
confusion_matrix(y_test,y_pred)

array([[ 20,  57],
       [ 43, 247]])

In [56]:
accuracy_score(y_test,y_pred)

0.7275204359673024

# Support Vector Machine

In [57]:
#Linear
from sklearn.svm import SVC
svl = SVC (kernel = 'linear')
# types of kernels are linear, sigmoid, Radial Basis Function(rbf), Polynomial
svl.fit(x_train, y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [58]:
y_pred = svl.predict(x_test)
y_pred


array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [59]:
confusion_matrix(y_test,y_pred)

array([[ 56,  21],
       [  1, 289]])

In [60]:
accuracy_score(y_test,y_pred)

0.9400544959128065

In [61]:
#Sigmoid
from sklearn.svm import SVC
svs = SVC (kernel = 'sigmoid')
# types of kernels are linear, sigmoid, Radial Basis Function(rbf), Polynomial
svs.fit(x_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [62]:
y_pred = svs.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [63]:
confusion_matrix(y_test,y_pred)

array([[  0,  77],
       [  0, 290]])

In [64]:
accuracy_score(y_test,y_pred)

0.7901907356948229

In [65]:
#rbf
from sklearn.svm import SVC
svr = SVC (kernel = 'rbf')
# types of kernels are linear, sigmoid, Radial Basis Function(rbf), Polynomial
svr.fit(x_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [66]:
y_pred = svr.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [67]:
confusion_matrix(y_test,y_pred)

array([[  1,  76],
       [  0, 290]])

In [68]:
accuracy_score(y_test,y_pred)

0.7929155313351499

In [69]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy')
dt.fit(x_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [70]:
y_pred = dt.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,

In [71]:
confusion_matrix(y_test,y_pred)

array([[ 60,  17],
       [ 63, 227]])

In [72]:
accuracy_score(y_test,y_pred)

0.782016348773842

In [73]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10,criterion = 'entropy')
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [74]:
y_pred = rfc.predict(x_test)

In [75]:
y_pred

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,

In [76]:
confusion_matrix(y_test,y_pred)

array([[ 68,   9],
       [ 21, 269]])

In [77]:
accuracy_score(y_test,y_pred)

0.9182561307901907

In [78]:
#Since we know now that the logistic model 
#is well accurate we will apply prediction to loan_predict again re-arranging x_test

In [79]:
loan_predict.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001015       1        1           0          0              0   
1  LP001022       1        1           1          0              0   
2  LP001031       1        1           2          0              0   
3  LP001035       1        1           2          0              0   
4  LP001051       1        0           0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                0.0       110.0               360   
1             3076             1500.0       126.0               360   
2             5000             1800.0       208.0               360   
3             2340             2546.0       100.0               360   
4             3276                0.0        78.0               360   

   Credit_History  Property_Area  
0               1              2  
1               1              2  
2               1              2  
3               1              2  
4               1              2

In [80]:
x_test = loan_predict.iloc[:,1:].values

# Logistic Regression model for Prediction

In [81]:
y_pred = lr.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [82]:
Predictions = pd.DataFrame(y_pred)

In [83]:
#concatenating the predicted data in loan_predict data which is processed
loan_predict = pd.concat([loan_predict,Predictions],axis = 1)

In [84]:
loan_predict.rename({0:'Predicted_Loan_Status'},axis=1,inplace=True)

In [85]:
loan_predict.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001015       1        1           0          0              0   
1  LP001022       1        1           1          0              0   
2  LP001031       1        1           2          0              0   
3  LP001035       1        1           2          0              0   
4  LP001051       1        0           0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                0.0       110.0               360   
1             3076             1500.0       126.0               360   
2             5000             1800.0       208.0               360   
3             2340             2546.0       100.0               360   
4             3276                0.0        78.0               360   

   Credit_History  Property_Area  Predicted_Loan_Status  
0               1              2                      1  
1               1              2                      1  
2               1              2                      1  
3               1              2                      1  
4               1              2                      1

In [86]:
#Or rather putting Back to original file to share it with team
loan_predict = pd.read_csv('/Users/umangpandya/Downloads/Class 9 - Codes/Project - Classification/Python_Module_Day_15.3_Credit_Risk_Test_data.csv')

In [87]:
loan_predict = pd.concat([loan_predict,Predictions],axis = 1)

In [88]:
loan_predict.rename({0:'Predicted_Loan_Status'},axis = 1,inplace=True)

In [89]:
loan_predict['Predicted_Loan_Status'].replace({0:'N',1:'Y'},inplace = True)

In [90]:
loan_predict.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area Predicted_Loan_Status  
0             1.0         Urban                     Y  
1             1.0         Urban                     Y  
2             1.0         Urban                     Y  
3             NaN         Urban                     Y  
4             1.0         Urban                     Y

In [92]:
loan_predict.to_csv('loan_predict')

In [93]:
os.getcwd()

'/Users/umangpandya'